<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 static/rigged.gltf --transform
-->

<script>
  import { Group } from 'three';
  import { T, forwardEventHandlers } from '@threlte/core';
  import { useGltf, useGltfAnimations } from '@threlte/extras';

  export const ref = new Group();

  const gltf = useGltf('/rigget_V16.glb', { useDraco: true });
  export const { actions, mixer } = useGltfAnimations(gltf, ref);

  const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="RootNode">
        <T is={gltf.nodes.rHand} />
        <T.SkinnedMesh
          name="Palms_Up_Together_Emoji_1_2"
          geometry={gltf.nodes.Palms_Up_Together_Emoji_1_2.geometry}
          material={gltf.materials.DefaultMaterial}
          skeleton={gltf.nodes.Palms_Up_Together_Emoji_1_2.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
